image: erlang:19

build_job:
  stage: build
  script:
    - rebar3 get-deps
    - rebar3 compile
  except:
    - tags

release_job:
  stage: release
  script:
    - rebar3 get-deps
    - rebar3 compile
    - rebar3 as prod release
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - _build/prod/rel/ircbot/
  only:
    - tags

stages:
  - build
  - test
  - release

cache:
  paths:
  - /root/.cache
  - _build/
