name: Make a release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: erlang:27

    steps:
    - uses: actions/checkout@v7

    - run: rebar3 compile
    - run: rebar3 as full tar

    - name: Create Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: _build/full/rel/ircbot/ircbot-1.0.0.tar.gz
        prerelease: true
        draft: true

